import { useEffect, useState } from 'react';
import { api, apiBlob } from '../services/api';

type Ticket = { id:string; user?:{ name:string; email:string; characterName?:string|null }; category:string; title:string; message:string; status:string; internalPriority:string; internalNote?:string|null; screen?:string|null; platform?:string|null; userAgent?:string|null; createdAt:string; messages?:Array<{id:string;message:string;isInternal?:boolean;createdAt:string;author?:{name:string}}> };
const statuses = ['OPEN','IN_REVIEW','ANSWERED','CLOSED','REJECTED'];
const priorities = ['LOW','MEDIUM','HIGH','CRITICAL'];

export function AdminSupportPanel() {
  const [tickets,setTickets]=useState<Ticket[]>([]); const [selected,setSelected]=useState<Ticket|null>(null);
  const [status,setStatus]=useState(''); const [priority,setPriority]=useState(''); const [note,setNote]=useState(''); const [response,setResponse]=useState(''); const [error,setError]=useState(''); const [message,setMessage]=useState('');
  async function load(){ const data=await api<{tickets:Ticket[]}>('/admin/support/tickets'); setTickets(data.tickets); }
  useEffect(()=>{load().catch((e)=>setError((e as Error).message));},[]);
  async function open(id:string){ const data=await api<{ticket:Ticket}>(`/admin/support/tickets/${id}`); setSelected(data.ticket); setStatus(data.ticket.status); setPriority(data.ticket.internalPriority); setNote(data.ticket.internalNote ?? ''); setResponse(''); }
  async function save(){ if(!selected)return; setError(''); setMessage(''); try{ const data=await api<{ticket:Ticket;message:string}>(`/admin/support/tickets/${selected.id}`,{method:'PATCH',body:JSON.stringify({status,internalPriority:priority,internalNote:note,response:response||undefined})}); setSelected(data.ticket); setMessage('Chamado atualizado.'); setResponse(''); await load(); }catch(e){setError((e as Error).message);} }
  async function exportCodex(){ const blob=await apiBlob('/admin/support/tickets/export/codex'); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download='rpc-support-codex-report.md'; a.click(); URL.revokeObjectURL(url); }
  return <section><div className="support-modal-header"><h3>💬 Suporte</h3><button className="button-primary" onClick={exportCodex}>Exportar para Codex</button></div>{error&&<p className="status-message error">{error}</p>}{message&&<p className="status-message success">{message}</p>}<div className="admin-support-grid"><div className="mobile-card-list">{tickets.map(t=><button key={t.id} className="summary-item compact-card support-ticket-card" onClick={()=>open(t.id)}><strong>{t.title}</strong><span>{t.category} • {t.status} • {t.internalPriority}</span><small>{t.user?.characterName ?? t.user?.name} — {new Date(t.createdAt).toLocaleString('pt-BR')}</small></button>)}</div>{selected&&<div className="nested-card"><h3>{selected.title}</h3><p><strong>Usuário:</strong> {selected.user?.characterName ?? selected.user?.name} ({selected.user?.email})</p><p><strong>Categoria:</strong> {selected.category}</p><p><strong>Tela/plataforma:</strong> {selected.screen ?? '-'} / {selected.platform ?? '-'}</p><p><strong>User-Agent:</strong> {selected.userAgent ?? '-'}</p><p>{selected.message}</p><div className="form-grid"><select value={status} onChange={e=>setStatus(e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select><select value={priority} onChange={e=>setPriority(e.target.value)}>{priorities.map(p=><option key={p}>{p}</option>)}</select><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Nota interna"/><textarea value={response} onChange={e=>setResponse(e.target.value)} placeholder="Resposta ao usuário"/><button className="button-primary" onClick={save}>Salvar atendimento</button></div><h4>Histórico</h4>{selected.messages?.map(m=><p key={m.id}><strong>{m.isInternal?'Nota interna':m.author?.name ?? 'Equipe'}:</strong> {m.message}</p>)}</div>}</div></section>;
}
